default 3308

label 3308
	menu label 3308
	linux /Image
	fdtdir /rockchip
	append root=/dev/mmcblk1p2 console=ttyS0,1500000n8 loglevel=9 rw rootwait coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 

label rk3308h2
	menu label 3308h2_64MB
	linux /Image
	fdtdir /rockchip
	append root=/dev/mmcblk1p2 console=ttyS0,1500000n8 loglevel=9 rw rootwait coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 mem=64

label rk3308h3
	menu label 3308h3_128MB
	linux /Image
	fdtdir /rockchip
	append root=/dev/mmcblk1p2 console=ttyS0,1500000n8 loglevel=9 rw rootwait coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 mem=128
