# from debian rock-s0_debian_bookworm_cli_b6.img
default l0
menu title U-Boot menu
prompt 1
timeout 1


label l0
	menu label 3308
	linux /Image
	fdtdir /rockchip
    append root=/dev/mmcblk1p2 console=ttyS0,1500000n8 loglevel=9 rw rootwait coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 
	
	#append root=/dev/mmcblk1p2 console=ttyS0,1500000n8 quiet splash loglevel=9 rw earlycon consoleblank=0  coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

	#append root=UUID=07e09376-a70a-4161-8ba0-0b5dc372a857 console=ttyS0,1500000n8 quiet splash loglevel=4 rw earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

#label l0r
#	menu label Debian GNU/Linux 12 (bookworm) 6.1.68-1-stable (rescue target)
#	linux /boot/vmlinuz-6.1.68-1-stable
#	initrd /boot/initrd.img-6.1.68-1-stable
#	fdtdir /usr/lib/linux-image-6.1.68-1-stable/
#	append root=UUID=07e09376-a70a-4161-8ba0-0b5dc372a857 console=ttyS0,1500000n8 splash loglevel=4 rw earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 single
#
